apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
spec:
  type: {{ .Values.rabbitmq.type }}
  selector:
    app: rabbitmq
  ports:
    - name: rabbitmq-amqp
      port: 5672
      targetPort: 5672
    - name: rabbitmq-http
      port: 15672
      targetPort: 15672