trigger: none

pool:
  vmImage: 'ubuntu-latest'

variables:
  - group: k8s-common
  - name: helmRepoName
    value: 'online-store-charts'
  - name: chartName 
    value: 'config'
  - name: helmChartPath 
    value: './multi-helmchart/'
  - name: helmChartVersion
    value: $(Build.BuildId)

stages:
  - stage: HelmPackagePush
    displayName: Helm Package and Push
    jobs:
    - job: Helm
      pool:
        vmImage: 'ubuntu-latest'
      steps:
        - template: appTemplates/helm-push.yml
          parameters:
            imageTag: $(imageTag)
            helmChartPath: $(helmChartPath)
            chartName: $(chartName)
            helmChartVersion: $(helmChartVersion) 
            helmRepoName: $(helmRepoName)
            acrName: $(acrName)
            serviceConnection: $(serviceConnection)

  - stage: Dev_Deploy
    displayName: Deploy to AKS Dev
    dependsOn: HelmPackagePush
    variables:
      - group: 'k8s-dev'
    jobs:
      - template: appTemplates/deploy.yml
        parameters:
            chartName: $(chartName)
            helmChartVersion: $(helmChartVersion) 
            helmRepoName: $(helmRepoName)
            acrName: $(acrName)
            aksCluster: $(aksCluster)
            aksResourceGroup: $(aksResourceGroup) 
            serviceConnection: $(serviceConnection)
            environment: dev
            namespace: $(namespace)
            helmChartPath: $(helmChartPath)

  - stage: Test_Deploy
    displayName: Deploy to AKS Test
    dependsOn: Dev_Deploy
    variables:
      - group: 'k8s-test'
    jobs:
      - template: appTemplates/deploy.yml
        parameters:
            chartName: $(chartName)
            helmChartVersion: $(helmChartVersion) 
            helmRepoName: $(helmRepoName)
            acrName: $(acrName)
            aksCluster: $(aksCluster)
            aksResourceGroup: $(aksResourceGroup) 
            serviceConnection: $(serviceConnection)
            environment: test
            namespace: $(namespace)
            helmChartPath: $(helmChartPath)

  - stage: Prod_Deploy
    displayName: Deploy to AKS Prod
    dependsOn: Test_Deploy
    variables:
      - group: 'k8s-prod'
    jobs:
      - template: appTemplates/deploy.yml
        parameters:
            chartName: $(chartName)
            helmChartVersion: $(helmChartVersion) 
            helmRepoName: $(helmRepoName)
            acrName: $(acrName)
            aksCluster: $(aksCluster)
            aksResourceGroup: $(aksResourceGroup) 
            serviceConnection: $(serviceConnection)
            environment: prod
            namespace: $(namespace)
            helmChartPath: $(helmChartPath)

  