trigger: none

pool:
  vmImage: 'ubuntu-latest'

variables:
  - group: k8s-common
  - name: helmRepoName
    value: 'online-store-charts'
  - name: chartName 
    value: 'config'
  - name: helmChartPath 
    value: './multi-helmchart/'
  - name: helmChartVersion
    value: $(Build.BuildId)

stages:
  - stage: HelmPackagePush
    displayName: Helm Package and Push
    jobs:
    - job: Helm
      pool:
        vmImage: 'ubuntu-latest'
      steps:
        - template: appTemplates/helm-push.yml
          parameters:
            imageTag: $(imageTag)
            helmChartPath: $(helmChartPath)
            chartName: $(chartName)
            helmChartVersion: $(helmChartVersion) 
            helmRepoName: $(helmRepoName)
            acrName: $(acrName)
            serviceConnection: $(serviceConnection)