trigger: none

pool:
  vmImage: 'ubuntu-latest'

variables:
  - group: k8s-common
  - name: helmRepoName
    value: 'online-store-charts'
  - name: chartName 
    value: 'product'
  - name: helmChartPath 
    value: './multi-helmchart/'
  - name: helmChartVersion
    value: '0.1.0'
  - name: imageTag
    value: $(Build.BuildId)
  - name: imageName
    value: 'product'

stages:
  - stage: Build
    displayName: Docker Build and Push
    jobs:
      - job: BuildPublishDockerImages
        displayName: Build nad push Docker Images
        steps:          
          - template: appTemplates/build.yml
            parameters:
              acrServiceConnection: $(acrServiceConnection)
              imageName: $(imageName)
              dockerFilePath: '$(Build.sourcesdirectory)/app/product-service/Dockerfile'
              tag: $(imageTag)

  - stage: HelmPackagePush
    displayName: Helm Package and Push
    jobs:
    - job: Helm
      pool:
        vmImage: 'ubuntu-latest'
      steps:
        - template: appTemplates/helm-push.yml
          parameters:
            imageTag: $(imageTag)
            helmChartPath: $(helmChartPath)
            chartName: $(chartName)
            helmChartVersion: $(helmChartVersion) 
            helmRepoName: $(helmRepoName)
            acrName: $(acrName)
            serviceConnection: $(serviceConnection)