trigger: none

pool:
  vmImage: 'ubuntu-latest'

variables:
  - group: k8s-common
  - name: helmRepoName
    value: 'online-store-charts'
  - name: chartName 
    value: 'rabbitmq'
  - name: helmChartPath 
    value: './multi-helmchart/'
  - name: helmChartVersion
    value: $(Build.BuildId)
  - name: imageTag
    value: '3.13'

stages:
  - stage: HelmPackagePush
    displayName: Helm Package and Push
    jobs:
    - job: Helm
      displayName: Helm Package and Push
      pool:
        vmImage: 'ubuntu-latest'
      steps:
        - template: appTemplates/helm-push.yml
          parameters:
            imageTag: $(imageTag)
            helmChartPath: $(helmChartPath)
            chartName: $(chartName)
            helmChartVersion: $(helmChartVersion) 
            helmRepoName: $(helmRepoName)
            acrName: $(acrName)
            serviceConnection: $(serviceConnection)